# __NumPy Arithmetic Statistical and String Functions__

## __Agenda__

In this lesson, we will cover the following concepts with the help of examples:
- Arithmetic Operations Using NumPy
  * Addition
  * Subtraction
  * Multiplication
  * Division
  * Power of
- Statistical Function in Numpy
  * Calculating Median, Mean, Standard Deviation, and Variance in the Array
  * Calculating Percentiles
- String Function in Numpy

## __1. Arithmetic Operations Using NumPy__ ##
### __1.1 Addition__ ###

In [1]:
# Perform element-wise addition of two arrays using the 'np.add' method
import numpy as np
a = np.array([30,20,10])
b = np.array([10,20,30])
result = np.add (a,b)
print(result)

[40 40 40]


### __1.2 Subtraction__ ###

In [2]:
# Perform element-wise subtraction of two arrays using 'np.subtract' method
a = np.array([[30,40,60], [50,70,90]])
b = np.array([[10,20,30], [40,30,80]])
result = np.subtract (a,b)
print(result)

[[20 20 30]
 [10 40 10]]


### __1.3 Multiplication__ ###

In [3]:
# Perform element-wise multiplication of two arrays using the 'np.multiply' method
a = np.array([30,20,10])
b = np.array([10,20,30])
result = np.multiply (a,b)
print(result)

[300 400 300]


### __1.4 Division__ ###

In [4]:
# Perform element-wise division of two arrays using the 'np.divide' method
a = np.array([[1,2,1],[2,2,3]])
b = np.array([3,4,5])
result = np.divide (a,b)
print(result)

[[0.33333333 0.5        0.2       ]
 [0.66666667 0.5        0.6       ]]


### __1.5 Power of__ ###

In [5]:
# Perform element-wise power operation where each element in 'a' is raised to the corresponding element in 'b' using the 'np.power' method
a = [2,2,2,2,2]
b = [2,3,4,5,6]
c = np.power(a,b)
print(c)

[ 4  8 16 32 64]


## __2. Statistical Function in Numpy__ ##
### __2.1 Calculating Median, Mean, Standard Deviation, and Variance in the Array__ ###

In [6]:
# Median
array = np.array([[4,3,2],[10,1,0],[5,8,24]])
np.median(array)
print(np.median(array))
# Mean
np.mean(array)
print(np.mean(array))
# Standard Deviation
np.std(array)
print(np.std(array))
# Variance
np.var(array)
print(np.var(array))

4.0
6.333333333333333
6.944222218666553
48.22222222222222


### __2.2 Calculating Percentiles__ ###
- The `np.percentile()` function is used to compute the nth percentile of the array elements.
- The nth percentile value should be in between 0 and 100.

In [7]:
# Find the value under the 50th percentile of the NumPy array.
np.percentile(array,50)

4.0

## __3. String Function in Numpy__ ##

In [8]:
# Perform element-wise string concatenation for two arrays of string
x = np.array(['Hello','World'])
y = np.array(['Welcome', 'Learners'])
result = np.char.add(x,y)
print(result) 

['HelloWelcome' 'WorldLearners']


In [9]:
# Replacing the old substring with the new substring
str = "Hello How Are You"
print(str)
z = np.char.replace (str, 'Hello', 'Hi')
print (z)

Hello How Are You
Hi How Are You


In [10]:
# Converting all lowercase characters in a string to uppercase and vice-versa
str1 = "hello how are you"
print(str1)
z = np.char.upper (str1)
print(z)
str2 = "GREETINGS OF THE DAY"
print(str2)
s = np.char.lower (str2)
print(s)

hello how are you
HELLO HOW ARE YOU
GREETINGS OF THE DAY
greetings of the day


## __Assisted Practice__

### __Problem Statement:__

Consider the following arrays:

- Arrays for Arithmetic Operations:
  * Array A: [15, 25, 35, 45, 55]
  * Array B: [5, 10, 15, 20, 25]

- Array for Statistical Operations:
  * Array C: [12, 22, 32, 42, 52, 62, 72, 82, 92, 102]

- Arrays for String Functions:
  * String Array X: ['Hello', 'Data', 'Science', 'Class', 'Learners']
  * String Array Y: ['World', 'Analysis', 'is', 'Fun', '2023']
  
  
__Steps to Perform:__

1. Perform element-wise addition, subtraction, multiplication, division, and power operations on Arrays A and B
2. Calculate the median, mean, standard deviation, and variance for Array C
3. Concatenate corresponding elements of String Arrays X and Y
4. Convert all elements in String Array X to uppercase
5. Replace a specific substring in String Array Y with another substring

### What Each Step Teaches: Detailed Explanations

#### **1. Arithmetic Operations in NumPy**
NumPy is designed for efficient, **element-wise mathematical operations** on entire arrays, not just single values.  
When you perform addition, subtraction, multiplication, division, or power operations on two arrays of the same shape, **NumPy applies the operation to each corresponding element in parallel**, leveraging optimized, compiled code under the hood.

**Why this matters:**  
- This vectorized approach is *orders of magnitude faster* than using for-loops in plain Python, especially for large datasets.
- It enables highly readable, concise code that closely matches mathematical notation.
- You can easily scale your analysis from small samples to millions of data points without rewriting your logic.

---

#### **2. Statistical Functions in NumPy**
NumPy provides efficient implementations for **common summary statistics**—such as mean, median, standard deviation, and variance—directly on arrays.

**Why this matters:**  
- These statistics are foundational for exploratory data analysis (EDA), signal processing, ML feature engineering, and quality control.
- Using built-in functions (`np.mean`, `np.std`, etc.) ensures both **accuracy** and **speed**, while reducing human error from manual calculations.
- NumPy operations are heavily optimized for both CPU and memory efficiency, critical for real-world engineering and scientific workflows.

---

#### **3. String Operations in NumPy**
NumPy’s `char` module brings **vectorized string processing** to arrays, allowing you to concatenate, transform case, or replace substrings across entire datasets in a single function call.

**Why this matters:**  
- **Vectorized string functions** process all elements of the array simultaneously, far outpacing for-loops in pure Python.
- String operations like concatenation, upper/lower case transformation, or pattern replacement are essential in tasks like data cleaning, report generation, and natural language preprocessing.
- Clean, concise code using `np.char.*` functions reduces complexity and improves reproducibility in data science pipelines.

---

#### **General Engineering & Data Science Perspective**
- **Element-wise array math** and **vectorized operations** are the bedrock of efficient scientific computing, analytics, and machine learning in Python.
- Using NumPy for these operations unlocks both **performance** and **clarity**, letting you focus on *what* you want to compute, not *how* to iterate.
- This paradigm—*write code that works on arrays, not elements*—scales from classroom examples to production data science and engineering solutions in industry.

---

**Key takeaway:**  
Mastering these operations is critical for anyone working in AI, ML, engineering, or data-driven domains—whether you’re building a predictive model, analyzing a sensor log, or automating a report.
m

In [ ]:
import numpy as np

# Arrays for Arithmetic Operations
A = np.array([15, 25, 35, 45, 55])
B = np.array([5, 10, 15, 20, 25])

# 1. Element-wise arithmetic
print("Element-wise addition:", A + B)         # [20 35 50 65 80]
print("Element-wise subtraction:", A - B)      # [10 15 20 25 30]
print("Element-wise multiplication:", A * B)   # [ 75 250 525 900 1375]
print("Element-wise division:", A / B)         # [3. 2.5 2.333... 2.25 2.2]
print("Element-wise power:", A ** 2)           # [ 225  625 1225 2025 3025]

# Array for Statistical Operations
C = np.array([12, 22, 32, 42, 52, 62, 72, 82, 92, 102])

# 2. Statistics
print("\nMedian of C:", np.median(C))            # 57.0
print("Mean of C:", np.mean(C))                  # 57.0
print("Standard deviation of C:", np.std(C))     # 28.7228...
print("Variance of C:", np.var(C))               # 825.0

# Arrays for String Functions
X = np.array(['Hello', 'Data', 'Science', 'Class', 'Learners'])
Y = np.array(['World', 'Analysis', 'is', 'Fun', '2023'])

# 3. Concatenate corresponding elements
concat_XY = np.char.add(X, " " + Y)
print("\nConcatenated X and Y:", concat_XY)

# 4. Convert all elements in String Array X to uppercase
X_upper = np.char.upper(X)
print("X in uppercase:", X_upper)

# 5. Replace a substring in String Array Y ('Fun' → 'Awesome')
Y_replaced = np.char.replace(Y, 'Fun', 'Awesome')
print("Y with 'Fun' replaced:", Y_replaced)
